# Generated by Django 5.2.3 on 2025-06-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_category_alter_contact_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='category',
        ),
    ]
